config/routes.rb
Cliq::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :location_suggestions

  root to: 'pages#home'
  ['help', 'contact', 'faq', 'about', 'terms'].each do |page|
    get "/#{page}", to: ("pages#" + "#{page}"), as: page 
  end

  get '/games', to: 'users#games', as: 'games'
  get '/won', to: 'users#won', as: 'won'
  get '/lost', to: 'users#lost', as: 'lost'
  get '/start', to: 'users#start', as: 'start'
  get '/store', to: 'users#store', as: 'store'
  get '/strange_store', to: 'users#strange_store', as: 'strange_store'
  get '/buy', to: 'users#buy', as: 'buy'

  get '/categories/:id/select', to: 'categories#select', as: 'choose_cat'
  get '/tutorial', to: 'categories#tutorial', as: 'tutorial'
  post '/tutorial_select', to: 'categories#tutorial_select', as: 'tutorial_select'

  resources :categories, only: [:index, :show] do 
    get '/choose', to: 'activities#choose', as: 'choose_activity'
  end


  resources :interests, only: [:create, :destroy]
  post '/interests/quick_create', to: 'interests#quick_create', as: 'quick_create' 
  
  resources :locations, only: [:index]
  
  resources :messages, only: [:index, :show]

  ["upcoming", "going", "past", "open", "hosted"].each do |type|
    get "events/#{type}", to: "events##{type}", as: "#{type}_events"
  end


  get '/events/public/new', to: 'events#public_new', as: 'public_events'
  get '/events/:id/chat', to: 'events#chat', as: 'event_chat'
  post '/events', to: 'events#public_create', as: 'public_events_create'
  resources :events, only: [:index, :show]
  resources :users do 
    resources :events, only: [:new, :create]
    get '/events/:id/accept', to: 'events#accept', as: 'accept'
    get '/events/:id/pass', to: 'events#pass', as: 'pass'
    get '/conversations/:id/searched', to: 'conversations#searched_show', as: 'searched_convo'
    get '/chat', to: 'conversations#chat', as: 'chat'
  end
  post '/events/toggle', to: 'events#toggle'
  post '/events/discuss_time', to: 'events#discuss_time'

  get '/users/:id/block', to: 'users#block', as: 'block_user'
  get '/users/:id/other', to: 'users#other', as: 'other_user'
  get '/users/:id/settings', to: 'users#settings', as: "settings"
  post '/users/invite_friends', to: 'users#invite_friends', as: "invite_friends"
  post '/users/welcome', to: 'users#welcome_update', as: 'welcome_update'
  get '/users/:id/result_info', to: 'users#result_info', as: 'result_info'
    
  resources :activities, only: [:index, :create]
  post '/users/:id/send_activation', to: 'users#send_activation', as: 'send_activation'
  get '/users/:id/activate/:code', to: 'users#activate', as: 'activate'
  get '/search', to: 'users#search', as: 'search'
  get '/main', to: 'users#main', as: 'main'
  post '/search', to: 'users#search_results'
  post '/feedback', to: 'users#feedback', as: 'feedback'
  get '/send_feedback', to: 'users#send_feedback', as: 'send_feedback'
  resources :partners, only: [:show]
  resources :conversations, only: [:show] do 
    resources :messages, only: [:create]
  end

  get '/backdoor/:password', to: 'users#backdoor'



 
  resources :partners
 
  resources :activities
 
  get '/auth/facebook/callback', :to => 'sessions#create'
  get '/auth/failure', :to => 'sessions#failure'
  get '/logout', :to => 'sessions#destroy'
end

app/models/message.rb
class Message < ActiveRecord::Base
	belongs_to :conversation, touch: true
	belongs_to :user
	validates :body, presence: true
	attr_accessible :body, :user_id, :conversation_id, :seen


	def date user
		(created_at + user.timezone.hours).strftime("%B %d")
	end

	def html_body
		text = body.gsub(/(<.*>).*(<.*>)/, "")
		text = text.gsub(/(<.*>)/, "")
		other_text = text.gsub(/\[link\]\((.*)\)/, "")
		match = Regexp.last_match(1)
		if match
			if match[0..6] != 'http://'
				url_match = 'http://' + match
			else
				url_match = match
			end
			text.gsub(/\[link\]\((.*)\)/, "<a href='#{url_match}'>#{match}</a>")
		else
			text
		end
	end
end

app/controllers/messages_controller.rb
	class MessagesController < ApplicationController
	include SessionsHelper
	include ApplicationHelper
	include ActionView::Helpers::JavaScriptHelper

	def index
		respond_to do |format|
      format.html { render :layout => !request.xhr? }
    end
	end

	def create
		@message = Message.new params[:message]
		@message.user_id = current_user.id
		@message.conversation_id = params[:conversation_id]
		@conversation = Conversation.find(params[:conversation_id])
		@user = @conversation.get_other_user current_user
		if @message.save && !current_user.blocked_by?(@user) 
			if !params[:event] == "true" || !params[:event]
				@conversation.update_attributes initiated: true
				@conversation.update_attributes connected: true if (@conversation.connected == false) && @conversation.messages.map(&:user_id).include?(@user.id)
				@user.message_count += 1 
				@user.save
				broadcast user_path(@user)+ "/messages", @message.to_json
				other_connection = Connection.where(conversation_id: params[:conversation_id], user_id: @user.id).first
				if @user.notify_messages && (!@user.active || !@user.using) && !other_connection.emailed
					other_connection.update_attributes emailed: true
					MessageMailerWorker.perform_async @user.id, current_user.id
				end
			else
				@conversation.email_all_others current_user
				@conversation.clear_seen_by current_user
				event = @conversation.event
				event.messages_count += 1
				event.save
				@conversation.all_others(current_user).each do |user|
					broadcast user_path(user) + "/messages", @message.to_json
				end
			end
		end	
		@event_message = (params[:event] == "true")	
	end

	def show
		@message = Message.find params[:id]
		conversation = @message.conversation
		conversation.update_notifications current_user
		@event_image = (conversation.event_id != nil)
		render partial: 'show', locals: {message: @message, event_image: @event_image}
	end

end

app/views/messages/_chat_history.html.erb
<% if conversation %>
	<div class="message-history">
		<% conversation.ordered_messages.each do |message| %>
			<%= render partial: 'show', locals: {message: message, event_image: false} %>
		<% end %>
	</div>
	<div class="message-form">
		<%= form_for [conversation, new_message], remote: true do |f| %>
			<%= f.text_area :body, id: 'chat-box' %>
			<%= f.submit :class => :hidden %>
		<% end %>
		<%= image_tag current_user.profile_pic_url, id: "chat-box-pic" %>
			<div id="message-actions">
						<%= link_to new_user_event_path(other_user), :class => "white invite-user", remote: true do %>
					<div class="sending-progress gray head-3 hidden">
						Sending...
					</div>
					<% end %>
					<div class="action-button white message-reply inv-btn mes-action reply">
						<div class="result-action hit-reply">REPLY</div>
					</div>
			</div>
		</div>
<% end %>
<script>
  $(document).ready(function(){
  	  $('img.svg').each(function(){
    var $img = $(this);
    var imgID = $img.attr('id');
    var imgClass = $img.attr('class');
    var imgURL = $img.attr('src');

    $.get(imgURL, function(data) {
        // Get the SVG tag, ignore the rest
        var $svg = $(data).find('svg');

        // Add replaced image's ID to the new SVG
        if(typeof imgID !== 'undefined') {
            $svg = $svg.attr('id', imgID);
        }
        // Add replaced image's classes to the new SVG
        if(typeof imgClass !== 'undefined') {
            $svg = $svg.attr('class', imgClass+' replaced-svg');
        }
        // Remove any invalid XML tags as per http://validator.w3.org
        $svg = $svg.removeAttr('xmlns:a');
        // Replace image with new SVG
        $img.replaceWith($svg);
    }, 'xml');
  });
  	})
</script>

app/views/messages/_reverse_show.html.erb
<div class="message-block">
	<% if message.user_id != current_user.id %>
		<div class="date sent head-6 light-gray">
			<%= message.date %>
		</div>
		<div class="message sent head-5">
			<%= message.body %>
		</div>
	<% else %>
		<div class="message received head-5">
			<%= message.body %>
		</div>
		<div class="date recieved head-6 light-gray">
			<%= message.date %>
		</div>
	<% end %>
</div>

app/views/messages/_show.html.erb
<% if message.user_id == current_user.id %>
	<div class="message-block sent <%= 'event-message' if event_image %> new" id="message-<%= message.id %>">
		<div class="date sent head-6 light-gray">
			<% if event_image %>
				<%= image_tag message.user.profile_pic_url, :class => "message-pic sent" %>
				<div class="message-name sent"><%= message.user.first_name %></div>	
			<% end %>
			<%= message.date current_user %>
		</div>
		<div class="message sent head-5">
			<%= message.html_body.html_safe %>
		</div>
	</div>
<% else %>
	<div class="message-block received <%= 'event-message' if event_image %> new" id="message-<%= message.id %>">
		<div class="message received head-5">
			<%= message.html_body.html_safe %>
		</div>
		<div class="date recieved head-6 light-gray">
			<% if event_image %>
				<%= image_tag message.user.profile_pic_url, :class => "message-pic received" %>
				<div class="message-name received"><%= message.user.first_name %></div>
			<% end %>
			<%= message.date current_user %>
		</div>
	</div>
<% end %>

app/views/messages/create.js.erb
if ($('.current-thread').length > 0) {
	$('.current-thread').find(".message-history").append("<%= escape_javascript render partial: 'show', locals: {message: @message, event_image: @event_message } %>");
} else {
	$(".message-history").append("<%= escape_javascript render partial: 'show', locals: {message: @message, event_image: @event_message } %>");
}

<% if !@event_message %>

	<% message = @conversation.last_message.gsub(/"/, '').html_safe %>
	$("#<%= @user.id %> .convo-details .convo-last-message").text("<%= message %>")
<% end %>



$('.message-history')[0].scrollTop = $('.message-history')[0].scrollHeight
$('.sending-progress').text('Done').addClass('animated fadeOut')
$('.sending-progress').bind('oanimationend animationend webkitAnimationEnd', function(){
	$('.sending-progress').hide()
})

app/views/messages/index.html+phone.erb
<% if current_user.ordered_conversations.length > 0 %>
<div id="messages-container" class="mobile">
	<div class="message-content-container">
		<div class="message-content">
			<div id="conversations">
				<% current_user.ordered_conversations.each do |convo| %>

					<% user = convo.get_other_user current_user %>
					<% if user %>
						<div class="conversation" id="<%= user.id %>">
							<%= link_to other_user_path(user), :class => "other-user", remote: true do %>
								<% if current_user.conversated_with? user %>
									<%= image_tag user.profile_pic_url || 'Cliq.svg', :class => "convo-pic #{user.color}" %>
								<% else %>
									<%= image_tag 'Cliq.svg', :class => "convo-pic #{user.color}" %>
								<% end %>
							<% end %>
							<%= link_to conversation_path(convo, phone: true), :class => "convo-link", remote: true do %>
								<div class="convo-details">
									<div class="convo-name head-5"><%= user.first_name %></div>
									<div class="convo-last-message head-5 gray"><%= convo.last_message %></div>
								</div>
							<% end %>
						</div>
					<% end %>
				<% end %>
			</div>
		</div>
		<div id="thread-container" class="hidden">
			<div id="messages-box">
				<%= render partial: 'chat_history', locals: {conversation: @conversation, other_user: @other_user, new_message: @message} %>
			</div>
			</div>
			</div>
		</div>
	</div>
	<div id="invite-modal-container" class="modal"></div>
</div>
<% end %>

<script>
	
</script>

app/views/messages/index.html.erb
<div id="messages-container">
	<div class="message-content-container">
		<div class="message-content">
			<% if current_user.ordered_conversations.length > 0 %>
			<div id="conversations">
				<% current_user.ordered_conversations.each do |convo| %>

					<% user = convo.get_other_user current_user %>
					<% if user %>
						<div class="conversation" id="<%= user.id %>">
							<%= link_to other_user_path(user), :class => "other-user", remote: true do %>
								<% if current_user.conversated_with? user %>
									<%= image_tag user.profile_pic_url || 'Cliq.svg', :class => "convo-pic #{user.color}" %>
								<% else %>
									<%= image_tag 'Cliq.svg', :class => "convo-pic #{user.color}" %>
								<% end %>
							<% end %>
							<%= link_to conversation_path(convo), :class => "convo-link", remote: true do %>
								<div class="convo-details">
									<div class="convo-name head-5"><%= user.first_name %></div>
									<div class="convo-date head-5"><%= convo.date current_user %></div>
									<div class="convo-school head-6 light-gray"><%= user.school %><%= "Random School" if !user.school %></div>
									<div class="convo-last-message head-5 gray"><%= convo.last_message %></div>
								</div>
							<% end %>
							<div class="convo-block head-5"><a class="block" data-confirm="This user will no longer be able to send you messages or invites. Are you sure you want to block <%= user.first_name %>?" data-remote="true" href="<%= block_user_path user %>">Block</a></div>
						</div>
					<% end %>
				<% end %>
			</div>
			<% else %>
			<h1 id="no-message">You currently have no messages.</h1>
			<% end %>
		</div>
		<div id="thread-container">
			<div id="messages-box">
			</div>
		</div>
	</div>
	<div id="invite-modal-container" class="modal"></div>
	<script>
		$($('.conversation')[0]).addClass('current')
		$($('.convo-link')[0]).click()
	</script>
</div>




	<script>
	$('.content-container').removeClass('landing')
</script>