config/routes.rb
Cliq::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :location_suggestions

  root to: 'pages#home'
  ['help', 'contact', 'faq', 'about', 'terms'].each do |page|
    get "/#{page}", to: ("pages#" + "#{page}"), as: page 
  end

  get '/games', to: 'users#games', as: 'games'
  get '/won', to: 'users#won', as: 'won'
  get '/lost', to: 'users#lost', as: 'lost'
  get '/start', to: 'users#start', as: 'start'
  get '/store', to: 'users#store', as: 'store'
  get '/strange_store', to: 'users#strange_store', as: 'strange_store'
  get '/buy', to: 'users#buy', as: 'buy'

  get '/categories/:id/select', to: 'categories#select', as: 'choose_cat'
  get '/tutorial', to: 'categories#tutorial', as: 'tutorial'
  post '/tutorial_select', to: 'categories#tutorial_select', as: 'tutorial_select'

  resources :categories, only: [:index, :show] do 
    get '/choose', to: 'activities#choose', as: 'choose_activity'
  end


  resources :interests, only: [:create, :destroy]
  post '/interests/quick_create', to: 'interests#quick_create', as: 'quick_create' 
  
  resources :locations, only: [:index]
  
  resources :messages, only: [:index, :show]

  ["upcoming", "going", "past", "open", "hosted"].each do |type|
    get "events/#{type}", to: "events##{type}", as: "#{type}_events"
  end


  get '/events/public/new', to: 'events#public_new', as: 'public_events'
  get '/events/:id/chat', to: 'events#chat', as: 'event_chat'
  post '/events', to: 'events#public_create', as: 'public_events_create'
  resources :events, only: [:index, :show]
  resources :users do 
    resources :events, only: [:new, :create]
    get '/events/:id/accept', to: 'events#accept', as: 'accept'
    get '/events/:id/pass', to: 'events#pass', as: 'pass'
    get '/conversations/:id/searched', to: 'conversations#searched_show', as: 'searched_convo'
    get '/chat', to: 'conversations#chat', as: 'chat'
  end
  post '/events/toggle', to: 'events#toggle'
  post '/events/discuss_time', to: 'events#discuss_time'

  get '/users/:id/block', to: 'users#block', as: 'block_user'
  get '/users/:id/other', to: 'users#other', as: 'other_user'
  get '/users/:id/settings', to: 'users#settings', as: "settings"
  post '/users/invite_friends', to: 'users#invite_friends', as: "invite_friends"
  post '/users/welcome', to: 'users#welcome_update', as: 'welcome_update'
  get '/users/:id/result_info', to: 'users#result_info', as: 'result_info'
    
  resources :activities, only: [:index, :create]
  post '/users/:id/send_activation', to: 'users#send_activation', as: 'send_activation'
  get '/users/:id/activate/:code', to: 'users#activate', as: 'activate'
  get '/search', to: 'users#search', as: 'search'
  get '/main', to: 'users#main', as: 'main'
  post '/search', to: 'users#search_results'
  post '/feedback', to: 'users#feedback', as: 'feedback'
  get '/send_feedback', to: 'users#send_feedback', as: 'send_feedback'
  resources :partners, only: [:show]
  resources :conversations, only: [:show] do 
    resources :messages, only: [:create]
  end

  get '/backdoor/:password', to: 'users#backdoor'



 
  resources :partners
 
  resources :activities
 
  get '/auth/facebook/callback', :to => 'sessions#create'
  get '/auth/failure', :to => 'sessions#failure'
  get '/logout', :to => 'sessions#destroy'
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_filter :get_user
	skip_before_action :require_login
	include ApplicationHelper


	def games
		if Game.last && !Game.all.last.won
			@game = Game.last
			@numbers = @game.numbers.split(",")
		else
			@numbers = [rand(9) + 1, rand(9) + 1, rand(9) + 1, rand(9) + 1]
			until @numbers.uniq.length == 4
				@numbers = [rand(9) + 1, rand(9) + 1, rand(9) + 1, rand(9) + 1]
			end
			@game = Game.create numbers: @numbers.join(",")
		end
		@ops = ["+", "-", "*", "/", "^", "!", "%"]
	end

	def store
		@list = "cat,hand,nose,eyes,wings".split(",")
		@names = {cat: "Cat", hand: "Extra hand", nose: "Nose", eyes: "Real eyes", wings: "buffalo wings"}
		@prices = {cat: 100, hand: 60, nose: 50, eyes: 150, wings: 400}
	end

	def strange_store
		@list = "color,better,ramen".split(",")
		@names = {color: "Add color", better: "better graphics", ramen: "The Ramen Profitable Startup"}
		@prices = {color: 50, better: 150, ramen: 2000}
	end

	def start
		broadcast "/games", {go: true}.to_json
		render nothing: true
	end

	def buy
		if params[:type] == "strange"
			current_user.update_attributes coins: params[:amount].to_i
		else
			current_user.update_attributes money: params[:amount].to_i
		end
		current_user.update_attributes additions: params[:shit].downcase.split(",").join(",")
		render nothing: true
	end

	def won
		@game = Game.last
		new_money = current_user.money + 1000
		user.update_attributes money: new_money 
		Game.last.update_attributes won: true
		broadcast "/games", {won: true}.to_json
		render nothing: true
	end

	def lost
		@game = Game.last
		Game.last.update_attributes won: true
		broadcast "/games", {won: false}.to_json
		render nothing: true
	end

	skip_before_filter :require_login, only: [:backdoor]

	def show
		if params[:id].to_i != current_user.id
			redirect_to user_path current_user 
			return
		end
		@welcome = params["welcome"]
		@category = Category.where(name: "Do").first
		@format = Category.self_format
		@formatted_interests = @user.formatted_interests
		@unformatted_interests = current_user.unformatted_interests @formatted_interests
		count = @unformatted_interests.length > 1 ? 1 : 0
		@sug_cat = Category.where(name: @unformatted_interests[count].first[0]).first if !@unformatted_interests.empty?
		@act = Activity.new
		respond_to do |format|
  		format.html { render :layout => !request.xhr? }
  		format.json { render :json => @user }
		end
	end

	def backdoor 
		session[:user_id] = 12 if params[:password] == ENV["PASSWORD"]
		redirect_to events_path
	end

	def other
		@user = User.find params[:id]
		@format = Category.other_format @user.first_name, @user.sex
		@formatted_interests = @user.formatted_interests
		@unformatted_interests = @user.unformatted_interests @formatted_interests
		render layout: false
	end

	def send_activation
		current_user.update_attributes email: params[:email]
		UserMailer.welcome_email(current_user, params[:email]).deliver
		render nothing: true
	end

	def activate
		if params[:code] == ENV['password']
			session[:user_id] = @user.id
		end

		if params[:code] == @user.activation
			session[:user_id] = @user.id
			@user.activate
			@message = "You have been activated"
			redirect_to events_path(verified: true) and return
		else
			@message = "Activation Failed"
			redirect_to search_path
		end
	end

	def search
		respond_to do |format|
      format.html { render :layout => !request.xhr? }
    end
	end

	def main
		respond_to do |format|
        format.html { render :layout => !request.xhr? }
    end
	end

	# category is for redirection to moodboard which requires a category id
	# no_id is to make mobile rendering faster
	def search_results 
		@category = Category.where(name: "Do").first
		@no_id = (params[:ids] == "")
		results = current_user.search_results params[:location_id], params[:location], params[:ids], @no_id
		render partial: "#{params[:type]}_results", locals: {results: results, category: @category}
	end

	def result_info
		result_user = User.find params[:id]
		mut = current_user.similarities_with result_user
		sim = current_user.similar_categories_with result_user
		render json: {mut: mut, sim: sim}
	end

	def feedback
		content = params[:content]
		FeedbackMailer.feedback(content, current_user).deliver
		current_user.update_attributes activation: "feedback"
		render nothing: true
	end

	def send_feedback
		
	end

	def settings
		redirect_to settings_path(current_user) if current_user.id != params[:id].to_i
		respond_to do |format|
      format.html { render :layout => !request.xhr? }
    end
	end

	def welcome_update
		p params
		puts "\n"
		current_user.update_attributes email: params[:email]
		ActivationMailerWorker.perform_async current_user.id, params[:email] if params[:send]
		render nothing: true
	end

	# if a new address is entered, geocode it, or else mark it as the same
	# if the new address is a new valid address, update the users lat long cordinartes and address
	# along with everything else and update normally if otherwise
	def update
		old_address = current_user.address
		if old_address != params[:user][:address]
			new_address = Geocoder.search(params[:user][:address])[0]
		else
			new_address = "same"
		end
		if new_address != nil && new_address != "same"
			cords = new_address.coordinates
			attrs = params[:user].merge({latitude: cords[0], longitude: cords[1], address: new_address.data["address_components"][0]["long_name"]})
			current_user.update_attributes attrs
			render nothing: true and return
		elsif new_address == "same"
			current_user.update_attributes params[:user]
			render nothing: true and return
		else
			render json: {error: true}
		end
	end

	def destroy
		current_user.messages.map(&:conversation).uniq.compact.each do |convo|
			convo.destroy
		end
		Event.where(creator_id: current_user.id).destroy_all
		current_user.destroy
		redirect_to root_path
	end

	def invite_friends
		UserMailer.invite_email(current_user, params[:email]).deliver
		render nothing: true
	end

	def block
		user_id = params[:id]
		current_user.update_blacklist user_id
		User.find(params[:id]).update_blacklist current_user.id
		render nothing: true 
	end
private
	def get_user
		@user = params[:user_id] ? User.find(params[:user_id]) : User.find(params[:id]) if params[:id]
	end
end

app/views/users/_mobile_interests.html.erb
<div class="interests-self">
		<div class="cat-collection">
			<% @unformatted_interests.each do |cat_acts| %>
					<div class="scroll-cat" id="c-<%= cat_acts.first[1].first.category_id %>">
<pre class="scroll-cat-name"><% cat_acts.first[1].first.category.mobile_name.each do |word| %><%= word %><br><% end %></pre>
						<%= image_tag (cat_acts.first[1].first.category.thumb_image_url ), :class => "scroll-cat-pic" %>
						<div class="overlay"></div>
					</div>
					<div class="scroll-acts hidden">
						<% cat_acts.first[1].first.category.activities.order(:name).each do |act| %>
							
								<div class="scroll-act <%= 'chosen' if cat_acts.first[1].include?(act) %>">
									<%= link_to interests_path(act_id: act.id, nothing: true), remote: true, method: :post, class: 'add-other-act' do %>
										<div class="scroll-act-name"><%= act.super_short_name %></div>
									<% end %>
								</div>
						<% end %>
					</div>
			<% end %>
		</div>


	<div class="all-scroll-acts">
	</div>
</div>

<script>
	ready = function(){
		$($('.overlay')[1]).trigger('touchstart')
		$('.all-scroll-acts').scroll(function(){
			$('.user-container')[0].scrollTop = 1000
		})
	}
	$(document).ready(ready)
	$(document).on('page:load', ready)
</script>

app/views/users/_mobile_search_results.html.erb
<% if results != "invalid" && results != nil %>
	<% if results.empty? %>
		<%= render partial: "no_one", locals: {results: false} %>
	<% end %> 
	<% results.each do |entry| %>
		<div class="result no-complete">
			<div class="action-button chat white inv-btn">			
					<%= link_to user_chat_path(entry[0]), :class => "white chat-user", remote: true do %>
						<%= image_tag "mobile-messages.svg", :class => "action-icon" %>
					<% end %>		
				</div>
			<%= link_to other_user_path(entry[0]), :class => "other-user", remote: true do %>
					<%= image_tag 'Cliq.svg', :class => "profile-pic-card #{entry[0].color}" %>
			<% end %>
			
			<div class="card-header">
				<%= link_to other_user_path(entry[0]), :class => "other-user", remote: true do %>
					<div class="card-name dark-gray"><%= entry[0].first_name %></div>
				<% end %>
				<div class="card-school light-gray"><%= entry[0].school %></div>
				<% if entry[0].active %>
					<!-- <div class="card-active green">Active</div> -->
				<% else %>
					<!-- <div class="card-active gray">Offline</div> -->
				<% end %>

			</div>

			<div class="similarities">
			
				<div class="suggestions">
					<div class="sug-label">You both like:</div>
					<% entry[1].shuffle[0..4].each do |suggestion| %>
						<div class="suggestion white"><%= suggestion.shortened_name %></div>
					<% end %>
				</div>

				<div class="sim-info">
					<div class="mutual">
						<%= image_tag "Mutual.svg", :class => "sim-label svg" %>
						<div class="sim dark-gray"><%= @no_id ? entry[1].length : current_user.similarities_with(entry[0]) %></div>
					</div>
				</div>
			</div>
		</div>
	<% end %>
<% else  %>
<div class="hidden" id="invalid">invalid</div>
<%= render partial: 'no_one', locals: {results: false} %>
<% end %>

app/views/users/_no_one.html.erb
<div id="no-one-around" class="no-one-around">
	<div id="pre-invite" class="pre-invite"> 
		<% if !results %>
			<p id="no-one-text" class="head-2 dark-gray">There seems to be no one around. Try searching for other interests or invite your friends to join Cliq!</p>

			<% if !browser.mobile? %>
				<p id="no-one-text" class="head-2 dark-gray">You can also<%= link_to "add", choose_cat_path(category), :class => "add light-turq" %>more interests to widen your pool of matches!</p>
			<% else %>
				<p id="no-one-text" class="head-2 dark-gray">You can also<%= link_to "add", user_path(current_user), :class => "add light-turq" %>more interests to widen your pool of matches!</p>
			<% end %>
		<% else %>
			<p id="no-one-text" class="head-2 dark-gray">You've passed on quite a few people, why not take a break and invite a friend?</p>
		<% end %>

		<div id="cliq-invite" class="head-2 cliq-invite">Invite</div>
		<% if results %>
			<div class="head-2 cliq-skip">Skip</div>
		<% end %>
	</div>

	<div id="post-invite" class="hidden post-invite">
		<div id="post-invite-content">
			<%= form_tag invite_friends_path, id: "friend-invite", remote: true do %>
				<div id="what-send" class="head-3 dark-gray">Here's what we'll send:</div>

				<p id="preview-text">
					SUBJECT: <%= current_user.first_name %> invited you to join Cliq!<br><br>

					Hey there!<br><br>

					Our mutual friend, <%= current_user.first_name %>, wants to personally invite you to join Cliq.<br><br>

					With Cliq, you can discreetly meet people in your area who love the same cool things as you. No one can ever see your last name and your picture only shows up to the specific people you're chatting with. So, you're just a first name to most and an added picture the size of a nickel to the few talking to you. Totally discreet.<br><br>

					Not interested in meeting people? You can still sign up to find out about cool events at UCF.<br><br>

					What are you waiting for? Sign up now at www.cliqwith.me
				</p>
				<div id="enter-email" class="head-3 dark-gray">Enter a friend's email here: </div>
				<%= text_field_tag :email, nil, id: "invite-email", placeholder: "email@email.com", :class => "head-3 dark-gray" %>
				<%= submit_tag "Send Invite", id: "send-cliq-invite", :class => "head-3" %>
				<div id="sent-invite" class="head-3 dark-gray hidden sent-invite">Sent</div>
			<% end %>
			<% if results %>
				<div class="head-2 cliq-skip post hidden">Keep Going</div>
			<% end %>
		</div>
	</div>
</div>

app/views/users/_side_nav.html.erb
<div class="extended-side-nav">
	

		<% if current_user %>
			<%= link_to events_path, remote: true, :class => 'tab', id: "events" do %>
				<div class="extended events <%= 'active' if active == :events %> side-icon" >
					<%= image_tag "Events.svg", :class => "nav-icon svg" %>
					<% if current_user.event_nots > 0 %>
							<div class="counter">
								<%= current_user.event_nots %>
							</div>
						<% else %>
							<div class="counter hidden">
								<%= current_user.event_nots %>
							</div>
						<% end %>
					<div class="icon-label main">Events</div>
				</div> 
			<% end %>
		
			<%= link_to messages_path, "data-no-turbolink" => true, remote: true, :class => 'tab', id: "messages" do %>
			<div class="extended messages <%= 'active' if active == :messages %> side-icon">
				<%= image_tag "Messages.svg", :class => "nav-icon svg" %>
				<div class="icon-label main">Messages</div>
				<% if current_user.message_count > 0 %>
					<div class="counter">
						<%= current_user.message_count%>
					</div>
				<% else %>
					<div class="counter hidden">
						<%= current_user.message_count %>
					</div>
				<% end %>
			</div>
		<% end %>

		<%= link_to search_path, "data-no-turbolink" => true, remote: true, :class => 'tab', id: "search" do %>
			<div class="extended search <%= 'active' if active == :search %> side-icon">
				<%= image_tag "Search.svg", :class => "nav-icon svg" %>
				<div class="icon-label main">Search</div>
			</div>
		<% end %>

		<%= link_to user_path(current_user), "data-no-turbolink" => true, remote: true, :class => 'tab', id: "profile" do %>
			<div class="extended search <%= 'active' if active == :profile %> side-icon">
				<%= image_tag "Profile.svg", :class => "nav-icon svg" %>
				<div class="icon-label main">Profile</div>
			</div>
		<% end %>


		<%= link_to settings_path(current_user), remote: true, :class => 'tab', id: "settings" do%>
			<div class="extended settings side-icon <%= 'active' if active == :settings %>" id="extended-settings" >
				<%= image_tag "Settings.svg", :class => "nav-icon svg" %>
				<div class="icon-label main">User Settings</div>
			</div>
		<% end %>
	<% end %>
	<div class="extended-options hidden">
		<%= link_to help_path do %>
			<div class="icon-label">Help</div>
		<% end %>
		<%= link_to contact_path do %>
			<div class="icon-label">Contact</div>
		<% end %>
		<%= link_to faq_path do %>
			<div class="icon-label">FAQ</div>
		<% end %>
		<%= link_to about_path do %>
		<div class="icon-label">About</div>
		<% end %>
		<%= link_to terms_path do %>
		<div class="icon-label light-gray terms">Terms and Privacy</div>
		<% end %>
		<% if current_user %>
			<%= link_to logout_path do %>
				<div class="icon-label" id="logout">Logout</div>
			<% end %>
		<% end %>
	</div>
</div>

app/views/users/_swipe_results.html.erb
<% if results != "invalid" && results != nil %>
	<% if results.empty? %>
		<div id='empty'>
			<%= render partial: "no_one", locals: {category: @category, results: false} %>
		</div>
	<% end %> 
	<% results.shuffle.each do |entry| %>
		<div class="swiped-result" id="u-<%= entry[0].id %>">
			<div class="swiped-content">
				<%= link_to other_user_path(entry[0]), :class => "other-user", remote: true do %>
						<%= image_tag entry[0].obscured_pic , :class => "swiped-profile-pic-card #{entry[0].color}" %>
				<% end %>

				<div class="search-button hidden">
					<%= image_tag "mobile-search.svg", :class => "search-icon" %>
				</div>
				
				<div class="card-header">
					<%= link_to other_user_path(entry[0]), :class => "other-user", remote: true do %>
					<div class="swiped-card-name head-2 dark-gray"><%= entry[0].first_name %></div>
					<% end %>
				</div>

				<div class="swiped-similarities">
					<div class="swiped-school">
						<%= entry[0].school %>
					</div>
				</div>


				<div class="suggestions-container touch-scroll">

					<div class="swiped-suggestions">
						<div class="swiped-suggestion dark-gray mutual-suggestion headers">
							<%= image_tag ('Mutual.svg'), :class => "swiped-sug-pic headers mutual svg" %>
							<div class="swiped-count mut-stat"></div>
						</div>
						<div class="swiped-suggestion dark-gray headers">
							<%= image_tag ('Similar.svg'), :class => "swiped-sug-pic headers sim svg" %>
							<div class="swiped-count sim-stat"></div>
						</div>

						<% current_user.top_shared(entry[0]).each do |suggestion| %>
							<div class="swiped-suggestion dark-gray">
								<div class="swiped-sug-name"><%= suggestion.name %></div>
								<%= image_tag (suggestion.image_url || 'cliq.png'), :class => "swiped-sug-pic" %>
							</div>
						<% end %>
					</div>

					<div class="swiped-actions">
						<div class="swipe-action-content">
							<div class="swipe-next">
								<%= image_tag "Next.svg", :class => "swiped-action-icon svg next-icon" %>
							</div>

							<div class="swipe-info">
								<%= link_to other_user_path(entry[0]), :class => "other-user", remote: true do %>
									<%= image_tag "Info.svg", :class => "info-icon" %>
								<% end %>
							</div>

							<div class="chat white inv-btn swiped">	
								<%= link_to user_chat_path(entry[0]), :class => "white chat-user", remote: true do %>
									<%= image_tag "messages-white.svg", :class => "swiped-action-icon chat-icon" %>
								<% end %>
							</div>	
						</div>
					</div>
				</div>
			</div>
		</div>
	<% end %>
	<script>
  $('img.svg').each(function(){
    var $img = $(this);
    var imgID = $img.attr('id');
    var imgClass = $img.attr('class');
    var imgURL = $img.attr('src');

    $.get(imgURL, function(data) {
        // Get the SVG tag, ignore the rest
        var $svg = $(data).find('svg');

        // Add replaced image's ID to the new SVG
        if(typeof imgID !== 'undefined') {
            $svg = $svg.attr('id', imgID);
        }
        // Add replaced image's classes to the new SVG
        if(typeof imgClass !== 'undefined') {
            $svg = $svg.attr('class', imgClass+' replaced-svg');
        }
        // Remove any invalid XML tags as per http://validator.w3.org
        $svg = $svg.removeAttr('xmlns:a');
        // Replace image with new SVG
        $img.replaceWith($svg);
    }, 'xml');
  });
</script>
<script>
	$('.mobile .search-button').show()
	var height = ($(window).height() - 278) + "px"
	var mobileHeight = ($(window).height() - 182) + "px"
	$('.suggestions-container').css('height', height)
	$('.mobile .suggestions-container').css('height', mobileHeight)
	//*$(window).resize(function(){
		//var newHeight = ($(window).height() - 278) + "px"
		//$('.suggestions-container').css('height', newHeight)
	//})
	$('.swiped-result').first().show()
</script>

<% else  %>
<div class="hidden" id="invalid">invalid</div>
<% end %>
<div id='empty' class="hidden empty">
	<%= render partial: "no_one", locals: {category: @category, results: true} %>
</div>

app/views/users/main.html.erb
	<div id="search-container">
		<div id="search-content">
			<div id="query">
				<%= form_tag search_path, id: "search-form", remote: true do %>
					<div id="query-row-1">
						<div id="query-1" class="white">I want to hang out near</div>
						<%= text_field_tag :location, nil, :class => "dark-gray search-term", id: "query-location", value: current_user.address, placeholder: "Anywhere" %>
						<%= hidden_field_tag "location_id" %>
						<%= hidden_field_tag "type", "swipe" %>
						<div id="query-2" class="white">with people interested in</div>
					</div>
					<div id="query-interests" class="dark-gray">
						<%= text_field_tag :activity, nil, :class => "query-interest search-term", placeholder: 'Stuff I Like' %>
					</div>
					<%= submit_tag "Shuffle", :class => "red head-3", id:"search-query" %> 
					<%= hidden_field_tag "ids" %>
				<% end %>
			</div>
		</div>
	</div>
	<script>
		$(document).ready(function(){
			$('#search-form').submit()
		})
	</script>

	<div id="results-container">
			<% if @user_empty %>
			<div class="no-int-container">
				<div class="no-ints">
					It looks like you don't have any interests yet.<br>
					Click <%= link_to "here", choose_cat_path(@category), id: "choose-cats" %> to add some!
				</div>
			</div>
		<% end %>
		<div id="swiped-content">
			<div id="results-header">
			</div>
			

			<div id="results">
				<% if !@user_empty %>
					<%= render partial: 'swipe_results', locals: {results: @results} %>
				<% end %>
			</div>
		</div>
	</div>


<div id="invite-modal-container" class="modal">

</div>
<div id="other-modal-container" class="modal">

</div>

<script>
<%= render partial: 'subscribe.js.erb' %>
</script>

<% if 1 == 2 %>
	
	<div id="activation-container">
		<div id="activation-form" class="dark-gray">
			<p id="top"><span class="heavy">Cliq is currently only available to students at UCF</span><br>
			Please enter your UCF email address and click the<br>
			activation link we send you to start using Cliq.</p>
				<%= form_tag send_activation_path(current_user), remote: true, class: "send-activation" do %>
					<%= text_field_tag :email, nil, placeholder: "Enter email address", class: 'email-activation'   %>
					<%= submit_tag "Send", class: "submit-email" %>
				<% end %>

				<div class="send-activation hidden" id="thank-you">
					<p>Thank You! Please check your email and refresh the page when you've been activated</p>
				</div>


			<p id="bottom"><span class="heavy">Not a UCF? Student?</span> You can still enter your email to receive<br>
			updates when we start expanding to other to schools.</p>
		</div>
	</div>
<% end %>
	<%= image_tag 'Do.svg', :class => "ac-image hidden", id: "Do" %>
	<%= image_tag 'Watch.svg', :class => "ac-image hidden", id: "Watch" %>
	<%= image_tag 'Music.svg', :class => "ac-image hidden", id: "Music" %>
	<%= image_tag 'Discuss.svg', :class => "ac-image hidden", id: "Discuss" %>
<script>
$('body').addClass('background-gray')
</script>

app/views/users/show.html.erb
	<div class="user-container">
		<div id="profile-container"> 
			<div class="profile-info">
				<%= image_tag @user.profile_pic_url, :class => "profile-pic" %>
				

					<div class="head-1" id="name-self"><%= @user.name %></div>
					<div class="head-4" id="school-self"><%= @user.school || "Not Listed" %></div>
					
					
					<div class="account-stats">
						<div class="head-4 stat" ><%= @user.attendings%> Events Attended</div>
						<div class="head-4 stat"><%= @user.conversations.where(connected: true).count %> People Met</div>
						<div class="head-4 stat"><%= @user.activities.length%> Interests Listed</div>
					</div>
				<div class="profile-actions green">
					<%= link_to choose_cat_path(@category) do %>
						<div class="bubble red" id="add-interests">+add interests</div>
					<% end %> 
					<div class="bubble orange" id="quick-add">Quick Add</div>
					<%= form_tag quick_create_path, id: "quick-search", class: "hidden", remote: true do %>
						<%= text_field_tag :activities, nil, id: "self-search", :class => "head-4 quick-search-acts", placeholder: "Type an Interest" %>
						<div class="hidden interest-info"></div>
						<%= hidden_field_tag :act_id %>
						<%= submit_tag "Add", id: "submit-quick-search", :class => "head-4 hidden" %>
					<% end %>
				</div> 
			</div>
		</div>
		<%= render partial: 'interests', locals: {user: @user, format: @format, formatted_interests: @formatted_interests} %>
	</div>
	<% if @welcome == "true" %>
		<div id="activation-container" class="welcome-container">
			<div id="welcome-form" class="dark-gray">
				<p id="top-welcome" class="head-4"><span class="heavy">If you're reading this, it's because you're awesome and someone told you about Cliq's private beta. Good for you. Welcome to Cliq!</p>
					
				<p id="bottom-welcome" class="head-5 gray">Is this email correct? This is just so that we can let you know about any messages/invites that you recieve. You can also update your email and toggle notifications in User Settings.</p>

				<%= form_tag welcome_update_path, :class => "welcome-form", remote: true do %>
					<%= text_field_tag :email, nil, value: current_user.email, :class=> "welcome-email" %>
				<% end %>

				<div id="got-it" class="head-4">Okay, got it!</div>
			</div>
		</div>
	<% end %>