config/routes.rb
Cliq::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :location_suggestions

  root to: 'pages#home'
  ['help', 'contact', 'faq', 'about', 'terms'].each do |page|
    get "/#{page}", to: ("pages#" + "#{page}"), as: page 
  end

  get '/games', to: 'users#games', as: 'games'
  get '/won', to: 'users#won', as: 'won'
  get '/lost', to: 'users#lost', as: 'lost'
  get '/start', to: 'users#start', as: 'start'
  get '/store', to: 'users#store', as: 'store'
  get '/strange_store', to: 'users#strange_store', as: 'strange_store'
  get '/buy', to: 'users#buy', as: 'buy'

  get '/categories/:id/select', to: 'categories#select', as: 'choose_cat'
  get '/tutorial', to: 'categories#tutorial', as: 'tutorial'
  post '/tutorial_select', to: 'categories#tutorial_select', as: 'tutorial_select'

  resources :categories, only: [:index, :show] do 
    get '/choose', to: 'activities#choose', as: 'choose_activity'
  end


  resources :interests, only: [:create, :destroy]
  post '/interests/quick_create', to: 'interests#quick_create', as: 'quick_create' 
  
  resources :locations, only: [:index]
  
  resources :messages, only: [:index, :show]

  ["upcoming", "going", "past", "open", "hosted"].each do |type|
    get "events/#{type}", to: "events##{type}", as: "#{type}_events"
  end


  get '/events/public/new', to: 'events#public_new', as: 'public_events'
  get '/events/:id/chat', to: 'events#chat', as: 'event_chat'
  post '/events', to: 'events#public_create', as: 'public_events_create'
  resources :events, only: [:index, :show]
  resources :users do 
    resources :events, only: [:new, :create]
    get '/events/:id/accept', to: 'events#accept', as: 'accept'
    get '/events/:id/pass', to: 'events#pass', as: 'pass'
    get '/conversations/:id/searched', to: 'conversations#searched_show', as: 'searched_convo'
    get '/chat', to: 'conversations#chat', as: 'chat'
  end
  post '/events/toggle', to: 'events#toggle'
  post '/events/discuss_time', to: 'events#discuss_time'

  get '/users/:id/block', to: 'users#block', as: 'block_user'
  get '/users/:id/other', to: 'users#other', as: 'other_user'
  get '/users/:id/settings', to: 'users#settings', as: "settings"
  post '/users/invite_friends', to: 'users#invite_friends', as: "invite_friends"
  post '/users/welcome', to: 'users#welcome_update', as: 'welcome_update'
  get '/users/:id/result_info', to: 'users#result_info', as: 'result_info'
    
  resources :activities, only: [:index, :create]
  post '/users/:id/send_activation', to: 'users#send_activation', as: 'send_activation'
  get '/users/:id/activate/:code', to: 'users#activate', as: 'activate'
  get '/search', to: 'users#search', as: 'search'
  get '/main', to: 'users#main', as: 'main'
  post '/search', to: 'users#search_results'
  post '/feedback', to: 'users#feedback', as: 'feedback'
  get '/send_feedback', to: 'users#send_feedback', as: 'send_feedback'
  resources :partners, only: [:show]
  resources :conversations, only: [:show] do 
    resources :messages, only: [:create]
  end

  get '/backdoor/:password', to: 'users#backdoor'



 
  resources :partners
 
  resources :activities
 
  get '/auth/facebook/callback', :to => 'sessions#create'
  get '/auth/failure', :to => 'sessions#failure'
  get '/logout', :to => 'sessions#destroy'
end

app/models/event.rb
class Event < ActiveRecord::Base
	belongs_to :partner
	has_many :users, through: :excursions
	has_many :excursions, dependent: :destroy 
	has_many :conversations, dependent: :destroy
	mount_uploader :image, ImageUploader

	validates :title, presence: true
	validates :start_time, presence: true

	attr_accessible :view, :creator_id, :title, :description, :location, :start_time, :end_time, :image, :attended, :partner_id, :quantity, :remote_image_url, :closed, :music, :discussion, :activity, :party, :show, :food, :games, :twenty_one, :paid, :event_type, :messages_count, :shaman
	
	def html_classes c_user
		"#{ ' today' if today?(c_user)}#{ ' tomorrow' if tommorow?(c_user)} #{ date(c_user)} #{tags}#{ ' hosting' if c_user == user}"
	end

	def html_description
		text = body.gsub(/(<.*>).*(<.*>)/, "")
		text = text.gsub(/(<.*>)/, "")
		other_text = text.gsub(/\[link\]\((.*)\)/, "")
		match = Regexp.last_match(1)
		if match
			if match[0..6] != 'http://'
				url_match = 'http://' + match
			else
				url_match = match
			end
			text.gsub(/\[link\]\((.*)\)/, "<a href='#{url_match}'>#{match}</a>")
		else
			text
		end
	end

	def self.adjust_time adjustment
		all.each do |event|
			event.start_time += adjustment.hours
			event.save
		end
	end

	def self.change_types
		Event.where(event_type: "Work").update_all event_type: "Hangout"
		Event.where(event_type: "Play").update_all event_type: "Party"
		Event.where(event_type: "Chill").update_all event_type: "Event"
	end

	def self.assign_and_return_new params
		total_params = params[:event]
		tags = params[:tags].downcase.split(',').map do |t|
			{t.to_sym => true}
		end.inject Hash.new, :merge
		total_params = total_params.merge tags
		total_params = total_params.merge({paid: true}) if params[:requirements] && params[:requirements].include?("Paid")
		Event.new total_params
	end

	def conversation
		conversations.first
	end

	def shortened_title
		title.length > 95 ? title[0..93] + "..." : title
	end

	def date user
		(start_time + user.timezone.hours).strftime("%B-%e").gsub("- ", "-")
	end

	def tags
		types = "#{event_type},#{' show' if show},#{' activity' if activity},#{' music' if music},#{' discussion' if discussion},#{' drinks' if party},#{' food' if food},#{' games' if games},#{' shaman' if shaman}"
		(types.split(",") - [""]).join.downcase
	end

	def self.update_message_counts
		all.each do |event|
			next if !event.conversations.first
			count = event.conversations.first.messages.count
		end
	end

	def self.update_creators
		all.each do |event|
			event.update_attributes creator_id: event.creator.id
		end
	end

	def user
		User.find creator_id
	end

	def creator
		excursions.where(created: true)[0].user if excursions.where(created: true)[0]
	end

	def full_time user
		if !today? user
			stime = (start_time + user.timezone.hours).strftime("%B %d at %I:%M %p")
		else
			stime = (start_time + user.timezone.hours).strftime("%B %d at %I:%M %p") 
		end
	end

	def time user
		stime = (start_time + user.timezone.hours).strftime("%I:%M %p").downcase 
	end

	def today? user
		start_time - Time.now.utc < 24.hours && (start_time + (user.timezone.hours)).beginning_of_day.day == user.user_time.beginning_of_day.day
	end

	def tommorow? user
		start_time - Time.now.utc < 48.hours && ((start_time + (user.timezone.hours)).beginning_of_day.day - 1) == user.user_time.beginning_of_day.day
	end

	def attendees
		excursions.where(accepted: true)
	end

	def accepted?
		excursions.where(accepted: false).empty?
	end

	def passed_by? user
		!Excursion.where(user_id: user.id, event_id: id, passed: true ).empty?
	end

	def untouched_by? user
		Excursion.where(user_id: user.id, event_id: id).empty?
	end

	def people_count
		excursions.where(accepted: true).count
	end

	def short_location
		location.length > 24 ? location[0..23] + ".." : location
	end

	def self.open user
		where('start_time > (?)', (user.user_time - 6.hours) ).order(:start_time).select { |event| !event.passed_by?(user) }
	end

	def self.hosted_by user
		invite_excursions = user.excursions.where(created: true)
		invite_excursions.map(&:event).compact.select { |event| event.start_time > (user.user_time - 6.hours) }.sort_by(&:start_time)
	end

	def self.past user
		user.excursions.where(accepted: true).map(&:event).select { |event| event.start_time < (user.user_time - 6.hours) }.sort_by(&:start_time).reverse
	end

	def self.joined_by user
		user.excursions.where(accepted: true).map(&:event).select { |event| event.start_time > (user.user_time - 6.hours) }.sort_by(&:start_time)
	end 

	def self.messaged_joined_by user
		user.excursions.where(accepted: true).map(&:event).select { |event| event.start_time > (user.user_time - 6.hours) && event.messages_count != 0 }.sort_by(&:start_time)
	end

	def joined_by user
		!excursions.where(accepted: true, user_id: user.id).empty?
	end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController #in severe need of refactoring
	include SessionsHelper
	include ApplicationHelper
	skip_before_filter  :verify_authenticity_token

	def index
		redirect_to games_path and return
		excursions = current_user.excursions 
		@sign_in = params[:sign_in]
		@open = true
		@event = Event.new
		@verified = params[:verified]
		@welcome = params[:welcome] || (!current_user.activated?)
		excursions.update_all seen: true
		respond_to do |format|
        format.html { render :layout => !request.xhr? }
    end
	end

	def hosted
		@events = Event.hosted_by current_user
		if request.variant == [:phone]
			render partial: 'mobile_events', locals: {events: @events, open: "create"}
		else
			render partial: 'events', locals: {events: @events, open: true}
		end
	end

	def going
		@events = Event.joined_by current_user
		@open = false
		if request.variant == [:phone]
			render partial: 'mobile_events', locals: {events: @events, open: @open}
		else
			render partial: 'events', locals: {events: @events, open: @open}
		end
	end

	def open
		@events = Event.open current_user
		@open = true
		if request.variant == [:phone]
			render partial: 'mobile_events', locals: {events: @events, open: @open}
		else
			render partial: 'events', locals: {events: @events, open: @open}
		end
	end

	def public_new
		@event = Event.new
		@user = current_user
		@user.create_click_count += 1
		@user.save
		render layout: false
	end

	# creates new event using custom assign_and_return_new event method if on desktop
	# desktop ui widget doesn't distinguish between am and pm so if on desktop, adjust time by 12 hours 
	# if time is pm, time is then converted to utc time by adjusting by user timezone
	# if there's an image, refresh is inevitable so redirect to back
	# render ok true if ok, and errors if not
	def public_create
		event = Event.assign_and_return_new params
		if event.save
			if !browser.mobile?
				if params[:event][:start_time].include? "pm"
					pm = true
				end
				pm ? event.start_time += 12.hours : nil
			end
			event.start_time -= current_user.timezone.hours
			event.users << [current_user]
			excursion = Excursion.where(event_id: event.id, user_id: current_user.id)[0]
			excursion.update_attributes created: true, accepted: true
			event.save
			redirect_to events_path and return	
		else
			render json: event.errors
		end
	end

	def accept
		excursion = Excursion.find_or_create_by(event_id: params[:id], user_id: current_user.id)
		excursion.update_attributes accepted: true
		render :nothing => true, :status => 200, :content_type => 'text/html'
	end

	def pass
		excursion = Excursion.find_or_create_by(event_id: params[:id], user_id: current_user.id)
		excursion.update_attributes passed: true
		render :nothing => true, :status => 200, :content_type => 'text/html'
	end

	def chat
		@event = Event.find params[:id]
		@conversation = Conversation.find_or_create_by(event_id: @event.id)
		
		if current_user.role != "admin"
			@event.views += 1
			@event.save
			new_count = current_user.event_view_count + 1
			current_user.update_attributes event_view_count: new_count
		end
		
		@message = Message.new
		@locked = (params[:locked] == "true")
		decrease_count = @conversation.was_seen_by current_user
		current_user.update_attributes(invite_count: 0) if decrease_count
		respond_to do |format|
      format.html { render :layout => !request.xhr? }
    end
	end

	def toggle
		new_count = current_user.toggle_count + 1
		current_user.update_attributes toggle_count: new_count
		render nothing: true
	end

	def discuss_time
		time = current_user.discuss_time + params[:elapsedTime].to_i
		time /= current_user.event_view_count
		current_user.update_attributes discuss_time: time 
		render nothing: true
	end
end

app/views/events/_events.html.erb
<div class="today-events event-date-type">
	<div class="date-header head-2">Today</div>
</div>
<div class="tommorow-events event-date-type">
	<div class="date-header head-2">Tomorrow</div>
</div>


<% events.each do |event| %>
	<% lock_status = !event.joined_by(current_user) %>
	<div class="upcoming-event<%= event.html_classes current_user %><%= ' joined' if !lock_status %> ">
		<div class="upcoming-event-picture">
			<%= image_tag event.image_url || "Cliq.svg", :class => "event-picture" %>
			<div class="event-title-overlay">
				<div class="event-title head-3">
					<%= link_to event_chat_path(event, locked: false), :class => "chat-user", remote: true do %>
						<%= event.shortened_title %>
					<% end %>
				</div>
				<div class="event-reqs head-4">
					<% if event.paid %>
						<div class="req">$$</div>
					<% end %>
				</div>
			</div>


			<div class="invite-overlay">
				<div class="invite-count"><%= event.people_count %> Going</div>
				
				<%= link_to event_chat_path(event, locked: false ), :class => "chat-user no-obscure", remote: true do %>
					<div class="invite-thread">Click to view thread</div>
				<% end %>
			</div>
		</div>
		
		<div class="upcoming-event-info">
			

		
			<div class="white upcoming-event-time invite-row head-4">
				<%= event.time current_user %>
			</div>
			<% if open && event.creator != current_user && lock_status %>
				<div class="invite-row pass-accept">
					<div class="invite-action-buttons">
						<%= link_to user_accept_path(current_user, event), id: "e-#{event.id}", remote: true, :class => "event-action join" do %>
							<div class="event-action-bar">
								<%= image_tag 'Join.svg', :class => "event-action-pic" %>
								<div class="event-action-text">Join</div>
							</div>
						<% end %>
						<%= link_to user_pass_path(current_user, event), id: "e-#{event.id}", remote: true, :class => "event-action pass" do %>
							<div class="event-action-bar right">
								<%= image_tag 'Pass.svg', :class => "event-action-pic" %>
								<div class="event-action-text">Pass</div>
							</div>
						<% end %>
					</div>
					<%= link_to event_chat_path(event, locked: false), :class => "chat-user no-obscure", remote: true do %>
						<div class="invite-thread bottom hidden view-thread">View</div>
					<% end %>
				</div>
			<% end %>

			<div class="gray upcoming-event-description invite-row">
				<%= event.description %>
			</div>

			<div class="event-tags">
				<% ["music", "discussion", "activity", "party", "food", "games", "show", "shaman"].each do |tag| %>
					<% if event.send(tag.to_sym) %>
							<% tag = "mus" if tag == "music" %>
							<% tag = "hookah" if tag == "shaman" %>
							<%= image_tag "#{tag.capitalize}.svg", :class => "event-tag" %>
					<% end %>
				<% end %>
			</div>
			<div class="invite-row invite-actions">
				<%= link_to event_chat_path(event, locked: false), :class => "chat-user no-obscure", remote: true do %>
					<div class="invite-thread bottom">
						<% if event.messages_count == 0 || event.conversations.first.was_seen_by?(current_user) %> 
							<%= image_tag "messages-white.svg", :class => "invite-messages-pic" %>
						<% else %>
							<%= image_tag "messages-white.svg", :class => "invite-messages-pic" %>
							<div class="new-tag <%= 'hidden' if lock_status %>">New!</div>
						<% end %>
					</div>
				<% end %>
			</div>

		</div>
	</div>
<% end %>
<% if events.empty? %>
	<div id="empty-events">No Events to Show</div>
<% end %>

app/views/events/_mobile_events.html.erb
<%= link_to public_events_path, :class => "public-event-create hidden", remote: true do %>
	<div class="create-event">
		<div class="create-event-text">
			Create Event
		</div>
	</div>
<% end %>


<% events.each do |event| %>
	<% joined = event.joined_by(current_user) %>
	<%= link_to event_chat_path(event, locked: false), :class => "chat-user no-obscure", remote: true do %>
		<div class="conversation<%= event.html_classes(current_user) %><%= ' joined' if joined %>">
			<%= image_tag event.image_url || 'Cliq.svg', :class => "convo-pic" %>
			<div class="convo-details">
				<div class="convo-name m1"><%= event.title %></div>
				<div class="event-line m1 light-turq"><%= event.full_time current_user %></div>
				<div class="event-line m1 gray">
					<div class="event-tags">
						<% ["music", "discussion", "activity", "party", "food", "games", "show", "shaman"].each do |tag| %>
							<% if event.send(tag.to_sym) %>
									<% tag = "mus" if tag == "music" %>
									<% tag = "Hookah" if tag == "shaman" %>
									<%= image_tag "#{tag.capitalize}.svg", :class => "event-tag" %>
							<% end %>
						<% end %>
					</div>
				</div>
			</div>
			
				<div id="e-<%= event.id %>" class="ev-overlay <%= 'hidden' if !(joined && (open == true)) %>">
					<div class="ev-overlay-text">Joined</div>
					<div class="ev-overlay-text small"><%= event.messages_count %> Messages</div>
				</div>
		</div>
	<% end %>	
<% end %>

<% if events.empty? %>
	<div class="no-events">No events to show.</div>
<% end %>

app/views/events/chat.html+phone.erb
<div class="chat-partial chat-events">
	<div id="<%= @event.id %>"></div>
	<div id="chat-header">
		<div id="chat-info" class="white">
			<div id="chat-name"><%= @event.title %></div>
			<div id="slide-up">^Slide this up to post^</div>
		</div>
	</div>
	<% untouched = @event.untouched_by? current_user %>
	<div id="chat-partial-content">
		<div class="event-box">
			<% if untouched %>
				<%= link_to user_accept_path(current_user, @event), id: "e-#{@event.id}", remote: true, :class => "event-action join" do %>
					<div class="event-action-bar">
						<%= image_tag 'Join.svg', :class => "event-action-pic" %>
						<div class="event-action-text">Join</div>
					</div>
				<% end %>
			<% end %>
			<div class="event-action-bar <%= 'touched' if !untouched %>">
				<div class="event-action-text-going">
					<%= @event.people_count %><br><span class="light-gray going-text">Going</span>
				</div>
			</div>
			<% if untouched %>
				<%= link_to user_pass_path(current_user, @event), id: "e-#{@event.id}", remote: true, :class => "event-action pass" do %>
					<div class="event-action-bar">
						<%= image_tag 'Pass.svg', :class => "event-action-pic" %>
						<div class="event-action-text">Pass</div>
					</div>
				<% end %>
			<% end %>
		</div>
		<div class="event-box">
			<div class="event-desc light-turq m2"><%= @event.time current_user %></div>
		</div>
		<div class="event-box">
			<div class="event-desc long m2"><%= @event.description %></div>
		</div>
		<div class="message-history chat <%= 'locked' if @locked %>">
			<% @conversation.ordered_messages.each do |message| %>
				<%= render partial: 'messages/show', locals: {message: message, event_image: true} %>
			<% end %>
	
		</div>
	
	</div>
		<div class="chat-window-footer">	
			<%= form_for [@conversation, @message], remote: true do |f| %>
				<%= f.text_area :body, id: 'chat-box', :class => "chat-box" %>
				<%= hidden_field_tag :event ,"true" %>
			<% end %>
			<div id="message-actions">
				<div class="action-button white message-reply inv-btn mes-action reply">
					<div class="result-action hit-reply">Post</div>
				</div>
			</div>
		</div>
</div>

<script>
	$('.message-history.chat').css('height', '+=50px')
</script>

app/views/events/index.html.erb
<div id="events-container" class="no-mobile">
	<div id="new-open-event" class="sift-state <%= 'hidden' if @welcome || @verified %>">
		<div class="plus">+</div><div class="create-event-text">New Open Invite</div>
		<div class="sift-text">Sift through Events</div>
		<%= image_tag "shovel.svg", :class => "sift-pic hidden svg" %>
	</div>
		<div id="invite-container">
			
			<% if @welcome || @verified %>
				<script>
					$('.extended-side-nav').hide()
				</script>
				<div class="tut-overlay"></div>
				<div id="tut-container">
					<div id="sift-option" class="tut-option">
						<div class="option-question">Looking to join something?</div>
						<div class="option-title roboto">Sift</div>
						<%= image_tag "shovel.svg", :class => "tut-sift-pic" %>
					</div>
					<div id="create-option" class="tut-option">
						<div class="option-question">Looking to bring in new people?</div>
						<div class="option-title roboto">Open Invite<br>+</div>
					</div>
				</div>
			<% end %>
			<div id="event-create" class="hidden pane inactive">
				<%= render partial: 'public_new' %>
			</div>
			<div id="invites" class="current pane filter-on">
				<div class="event-form-right">
					<div class="form-row">
						<div class="event-quest">I'm looking for a</div>
						<div class="event-types">
							<div class="event-type round-left <%= 'selected' if @sign_in %>">Hangout</div>
							<div class="event-type">Party</div>
							<div class="event-type round-right">Event</div>
						</div>
					</div>
					<div class="form-row">
						<div class="event-attrs-1">
							<div class="event-attr no-left music">
								<%= image_tag "Mus.svg", :class => "attr-pic svg" %>
								<div class="attr-text">Music</div>
							</div>
							<div class="event-attr discussion">
								<%= image_tag "Discussion.svg", :class => "attr-pic svg" %>
								<div class="attr-text">Discussion</div>
							</div>
							<div class="event-attr activity">
								<%= image_tag "Activity.svg", :class => "attr-pic svg" %>
								<div class="attr-text">Activity</div>
							</div>
							<div class="event-attr party">
								<%= image_tag "Party.svg", :class => "attr-pic svg" %>
								<div class="attr-text">Drinks</div>
							</div>
						</div>
						<div class="event-attrs-2 food">
							<div class="event-attr food no-left">
								<%= image_tag "Food.svg", :class => "attr-pic svg" %>
								<div class="attr-text">Food</div>
							</div>
							<div class="event-attr games">
								<%= image_tag "Games.svg", :class => "attr-pic svg" %>
								<div class="attr-text">Games</div>
							</div>
							<div class="event-attr show">
								<%= image_tag "Show.svg", :class => "attr-pic svg" %>
								<div class="attr-text">A Show</div>
							</div>
							<div class="event-attr shaman">
								<%= image_tag "Hookah.svg", :class => "attr-pic svg" %>
								<div class="attr-text">A Shaman</div>
							</div>
						</div>
					</div>
					<div class="form-row event-dates">
						<div class="event-date-types gray">
							<div class="event-type round-left <%= 'selected' if @sign_in %>">Today</div>
							<div class="event-type">Tomorrow</div>
							<div class="event-type round-right">Any Time</div>
						</div>
					</div>

				</div>
					
			</div>
		</div>
	</div>

		<div id="other-events-container">
		<div id="events-header-actions" class="<%= 'hidden' if @welcome || @verified %>">
			<div id="upcoming-header" class="head-4 dark-gray">Open Events:</div>
				<div class="event-filter head-5 dark-gray selected" id="event-open">Open</div>
				<div class="event-filter head-5 dark-gray" id="event-going">Joined</div>
				<div class=" event-filter head-5 dark-gray" id="event-hosting">Hosting</div>
		</div>
			<div id="upcoming">
				<div id="events-box">
					<% if @welcome %>
						<div id="tut-content" class="animated bounceInDown">
							<div id="tut-1">
								<div class="tut-text">
									Welcome to Cliq! We're currently running a pilot at the University of Central Florida. To start using Cliq, we'll need you to enter your ucf.edu email and click the confirmation link we send you. 
								</div>
								<div class="sub-text">
									This is to ensure your safety and privacy. We will NEVER share your personal information with anyone. 
								</div>
								<%= form_tag welcome_update_path, :class => "confirmation-form", remote: true do %>
									<%= text_field_tag :email, nil, :class=> "welcome-email", placeholder: "Enter Valid UCF Email" %>
									<%= hidden_field :send, true %>
									<div class="confirmation">Send Confirmation</div>
								<% end %>
							</div>
						</div>
						<script>
			        $(document).ready(function() {
			           $(".confirmation-form").bind("keypress", function(e) {
			              if (e.keyCode == 13) {
			                 return false;
			              }
			           });
			        });
						</script>
					<% end %>
					<% if @verified %>
						<div id="tut-content" class="animated bounceInDown">
							<div id="tut-2">
								<div class="tut-text">
									Cliq is for meeting new people through open invites and having a good time. Anyone can host hangouts which show up to people from <span class="yellow">UCF</span>. 
								</div>
								<div class="tut-text">
									You can sift through hangouts and events to find the ones relevant to your interests and chat with people about plans.
								</div>
								<div class="tut-text">
									Or if you have a car, party, idea, Xbox, or playing cards, you can put up an <span class="red">Open Invite</span> for people to come hang out.  
								</div>
								<div class="confirmation got-it">Sweet, got it.</div>
							</div>
							<div id="tut-3" class="hidden">
								<div class="tut-text">
									Awesome you're all set!
								</div>
								<div class="tut-text">
									Remember to keep an eye out for cliq hosted hangouts every week. We'll have brownie giveaways, gaming sessions, water balloon fights, and a ton of cool events.
								</div>
								<div class="tut-text">
									Pick one of the two options on the left to get started  
								</div>
							</div>
						</div>
					<% end %>
			</div>
		</div>
		<div id="invite-modal-container" class="modal"></div>
	</div>

<%= link_to open_events_path, :class => "event-sort", remote: true do %>
	<div class="head-4 dark-gray selected hidden">Open</div>
<% end %>

<% if !@welcome && !@verified %>
	<script>
		$('.event-sort').first().click()
	</script>
<% end %>

	
<script>
	$('.content-container').removeClass('landing')
	function linkify(inputText) {
    var replacedText, replacePattern1, replacePattern2, replacePattern3;

    //URLs starting with http://, https://, or ftp://
    replacePattern1 = /(\b(https?|ftp):\/\/[-A-Z0-9+&@#\/%?=~_|!:,.;]*[-A-Z0-9+&@#\/%=~_|])/gim;
    replacedText = inputText.replace(replacePattern1, '<a href="$1" target="_blank">$1</a>');

    //URLs starting with "www." (without // before it, or it'd re-link the ones done above).
    replacePattern2 = /(^|[^\/])(www\.[\S]+(\b|$))/gim;
    replacedText = replacedText.replace(replacePattern2, '$1<a href="http://$2" target="_blank">$2</a>');

    //Change email addresses to mailto:: links.
    replacePattern3 = /(([a-zA-Z0-9\-\_\.])+@[a-zA-Z\_]+?(\.[a-zA-Z]{2,6})+)/gim;
    replacedText = replacedText.replace(replacePattern3, '<a href="mailto:$1">$1</a>');

    return replacedText;
}
</script>