config/routes.rb
Cliq::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :location_suggestions

  root to: 'pages#home'
  ['help', 'contact', 'faq', 'about', 'terms'].each do |page|
    get "/#{page}", to: ("pages#" + "#{page}"), as: page 
  end

  get '/games', to: 'users#games', as: 'games'
  get '/won', to: 'users#won', as: 'won'
  get '/lost', to: 'users#lost', as: 'lost'
  get '/start', to: 'users#start', as: 'start'
  get '/store', to: 'users#store', as: 'store'
  get '/strange_store', to: 'users#strange_store', as: 'strange_store'
  get '/buy', to: 'users#buy', as: 'buy'

  get '/categories/:id/select', to: 'categories#select', as: 'choose_cat'
  get '/tutorial', to: 'categories#tutorial', as: 'tutorial'
  post '/tutorial_select', to: 'categories#tutorial_select', as: 'tutorial_select'

  resources :categories, only: [:index, :show] do 
    get '/choose', to: 'activities#choose', as: 'choose_activity'
  end


  resources :interests, only: [:create, :destroy]
  post '/interests/quick_create', to: 'interests#quick_create', as: 'quick_create' 
  
  resources :locations, only: [:index]
  
  resources :messages, only: [:index, :show]

  ["upcoming", "going", "past", "open", "hosted"].each do |type|
    get "events/#{type}", to: "events##{type}", as: "#{type}_events"
  end


  get '/events/public/new', to: 'events#public_new', as: 'public_events'
  get '/events/:id/chat', to: 'events#chat', as: 'event_chat'
  post '/events', to: 'events#public_create', as: 'public_events_create'
  resources :events, only: [:index, :show]
  resources :users do 
    resources :events, only: [:new, :create]
    get '/events/:id/accept', to: 'events#accept', as: 'accept'
    get '/events/:id/pass', to: 'events#pass', as: 'pass'
    get '/conversations/:id/searched', to: 'conversations#searched_show', as: 'searched_convo'
    get '/chat', to: 'conversations#chat', as: 'chat'
  end
  post '/events/toggle', to: 'events#toggle'
  post '/events/discuss_time', to: 'events#discuss_time'

  get '/users/:id/block', to: 'users#block', as: 'block_user'
  get '/users/:id/other', to: 'users#other', as: 'other_user'
  get '/users/:id/settings', to: 'users#settings', as: "settings"
  post '/users/invite_friends', to: 'users#invite_friends', as: "invite_friends"
  post '/users/welcome', to: 'users#welcome_update', as: 'welcome_update'
  get '/users/:id/result_info', to: 'users#result_info', as: 'result_info'
    
  resources :activities, only: [:index, :create]
  post '/users/:id/send_activation', to: 'users#send_activation', as: 'send_activation'
  get '/users/:id/activate/:code', to: 'users#activate', as: 'activate'
  get '/search', to: 'users#search', as: 'search'
  get '/main', to: 'users#main', as: 'main'
  post '/search', to: 'users#search_results'
  post '/feedback', to: 'users#feedback', as: 'feedback'
  get '/send_feedback', to: 'users#send_feedback', as: 'send_feedback'
  resources :partners, only: [:show]
  resources :conversations, only: [:show] do 
    resources :messages, only: [:create]
  end

  get '/backdoor/:password', to: 'users#backdoor'



 
  resources :partners
 
  resources :activities
 
  get '/auth/facebook/callback', :to => 'sessions#create'
  get '/auth/failure', :to => 'sessions#failure'
  get '/logout', :to => 'sessions#destroy'
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :activities
	has_many :users, through: :cat_interests
	has_many :cat_interests
	has_ancestry

	attr_accessible :name, :description, :parent_id, :parent, :question, :alt_text, :image, :image_url, :popularity, :ancestry

	def user_likes user
		user.interests.map(&:activity).map(&:category).map(&:root).map(&:id).count id
	end

	def liked_not_liked_activities user
		ids = user.interests.map(&:activity_id)
		return [[], activities] if ids == []
		[activities.where('id in (?)', ids).where(suggested_by: nil).order('LOWER(name)'), activities.where('id not in (?)', ids).where(suggested_by: nil).order('LOWER(name)')]
	end

	def ask
	 	if parent && parent.name == "Music"
	 		inherited_question = parent.question.gsub parent.name.downcase, "#{name} #{parent.name.downcase}"
	 	elsif depth < 2 
	 		question
	 	else
	 		inherited_question = parent.question.gsub parent.name.downcase, "#{name} #{parent.name.downcase}"
	 	end
	end

	def self.main
		where(ancestry: nil).order :name
	end

	def self.self_format
		cats = Category.where(ancestry: nil).order(:name)
		[["Stuff you do for fun:", "Do", cats[1].id],["Music:", "Music", cats[2].id],["What you watch:", "Watch", cats[3].id], ["What you talk about:", "Discuss", cats[0].id]] 
	end

	def self.other_format name, sex
		pronoun = sex == "male" ? "he" : "she"
		[["Stuff #{name} does for fun:", "Do"],["What #{pronoun} listens to:", "Music"],["What #{pronoun} watches:", "Watch"], ["What #{pronoun} likes to talk about:", "Discuss"]] 
	end

	def image_url
		url_name = name.split.map do |word|
			word[0].upcase + word[1..-1]
		end	
		url_name = url_name.join("_") + ".jpg"
		if parent && parent.name == "TV Shows"
			url_name = "TV" + url_name
		end
		'https://s3.amazonaws.com/CliqBucket/Categories/' + url_name
	end

	def thumb_image_url
		image_url.gsub(".jpg", "_Thumbnail.jpg")
	end

	def full_name
		if depth > 1
			name + " " + parent.name
		else
			name
		end
	end

	def selected user
		!user.cat_interests.where(category_id: id).empty?
	end

	def short_name
		short = name[0..19]
		short += "..." if short.length == 20
		short
	end

	def mobile_name 
		split_name = name.split(" ")
		mobile = []
		split_name.each do |word|
			if !mobile.last
				mobile << word
			elsif mobile[-1].length > 5
				mobile << word
			else
				mobile[-1] += " #{word}"
			end
		end
		mobile
	end

	def self.update_top
		where('ancestry is not null').each do |cat|
			pop = cat.activities.map(&:interests).count
			cat.update_attributes popularity: pop
		end
	end

	def self.top cats, limit
		cats.order(:popularity).reverse[0..limit]
	end

	def self.partitioned_top limit
		cats = where(ancestry: nil).map do |cat|
			top cat.children, limit
		end
		cats.flatten
	end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	include SessionsHelper
	

	def select
		@category = Category.find params[:id]
		@interests = current_user.interests.count
		@act = Activity.new
		@categories = Category.main

		@activities = @category.activities
		acts = @category.liked_not_liked_activities current_user
		@liked = acts[0]
		@not_liked = acts[1]
	end

	def show
		category = Category.find params[:id]
		act = Activity.new
		activities = category.activities
		acts = category.liked_not_liked_activities current_user
		liked = acts[0]
		not_liked = acts[1]
		render partial: 'show', locals: {category: category, act: act, activities: activities, liked: liked, not_liked: not_liked}
	end

	def tutorial
		@characters = ["Athlete", "Corporate_Baller", "Intellectual", "Partier", "Maverick", "Shaman", "Gamer", "Creative"]
	end

	def tutorial_select
		current_user.update_attributes school: params[:school], characters: params[:characters]
		@act_list = current_user.interests.pluck(:activity_id)
		@categories = current_user.char_categories
		@act = Activity.new
		@category = @categories[1]
	end
end

app/views/categories/_show.html.erb
<% if category.has_children? %>
	<div id="categories-content-container">
		<div id="cat-content">
			<div id="cat-question" class="head-2 dark-gray">
				<%= category.ask %>
			</div>
			<% if category.parent %>
				<% p category.parent; puts "\n" * 10 %>
				<%= link_to category_path(category.parent), remote: true, class: 'back-link' do  %>
					<div id="cat-back" class="gray head-3">
						<span id="back-text"><< Back to <%= category.parent.name %></span>
					</div>
				<% end %>
			<% end %>
			<div id="cat-question-details" class="head-4 gray">
				(Click a panel to add some details. You can choose more than one.)
			</div>

			<div id="cat-list">
				<% category.children.each do |cat| %>
					<% if !cat.children.empty? %>
						<%= link_to category_path(cat), remote: true, class: 'cat-link' do %>
							<div class="cat">
								<div class="cat-title dark-gray head-4 <%= "prev-selected" if cat.selected current_user %>">
									<span class="cat-select"><%= cat.short_name %></span>
								</div>
								<%= image_tag cat.image_url, :class => "cat-pic" %>
							</div>
						<% end %>
					<% else %>
						<%= link_to category_choose_activity_path(cat), remote: true, class: 'cat-link' do %>
							<div class="cat">
								<div class="cat-title dark-gray head-4 <%= "prev-selected" if cat.selected current_user %>">
									<span class="cat-select"><%= cat.short_name %></span>
								</div>
								<%= image_tag cat.image_url, :class => "cat-pic" %>
							</div>
						<% end %>
					<% end %>
				<% end %>

			</div>
		</div>
	</div>

	<script>
		$('#activity_category_id').val('<%= category.id %>')
	</script>
<% else %>
	<%= render partial: 'activities/choose', locals: {category: category, activities: activities, liked: liked, not_liked: not_liked} %>
	<% puts "\n" * 100 %>

<% end %>

app/views/categories/index.html.erb
<div class="content-container">
	<%= render partial: 'users/side_nav', locals: {active: :profile} %>

	<div id="categories-header">
		<div id="cat-header-content" class="head-4 dark-gray">
			What do you
			<span id="do" class="cat-action doing">Do</span>
			<span id="listen-to" class="cat-action">Listen to</span>
			<span id="watch" class="cat-action">Watch</span>
			<span id="discuss" class="cat-action">Discuss</span>
			?
		</div>
	</div>



		<%= render partial: 'show', locals: {category: @category} %>

	<div id="categories-footer">
			<% if @likes < 8 %>
				<div id="cat-footer-content" class="head-4 gray">
					<div id="cat-footer-text">
						<p id="line-1">pick <span class="dark-gray" id="like-count"> <%= 8 - @likes %></span> or more options from any combination of categories to move on to the next section!</p>
						<p id="line-2">
							you can always come back to edit your choices
						</p>
					</div>
				</div>
				<div id="next-cat" class="hidden head-3 dark-gray">NEXT</div>
			<% else %>
				<div id="cat-footer-content" class="head-4 gray hidden">
					<div id="cat-footer-text">
						<p id="line-1">pick <span class="dark-gray" id="like-count"> <%= 8 - @likes %></span> or more options from any combination of categories to move on to the next section!</p>
						<p id="line-2">
							you can always come back to edit your choices
						</p>
					</div>
				</div>
				<div id="next-cat" class="head-3 dark-gray">NEXT</div>
			<% end %>
	</div>
</div>

app/views/categories/select.html.erb
	<%= render partial: 'users/side_nav', locals: {active: :profile} %>


	<div id="categories-header">
		
		<div id="cat-header-profile">
			<%= image_tag current_user.profile_pic_url, :class => "cat-profile-pic" %>
			<div class="cat-profile-name head-2 white"><%= current_user.name %></div><br>
			<div class="cat-profile-school white"><%= current_user.school %></div>
		</div>
		<br>
		<div id="cat-header-content" class="head-4 dark-gray">
			<div class="header-pre">What do you</div>
			<div class="header-row">
				<%= link_to choose_cat_path @categories[1] do %>
					<div id="do" class="cat-action <%= doing? 'Do' %> ">Do</div>
				<% end %>
				<%= link_to choose_cat_path @categories[2] do %>
					<div id="listen-to" class="cat-action <%= doing? 'Music' %>">Listen to</div>
				<% end %>
			</div>
			<div class="header-row">
				<%= link_to choose_cat_path @categories[3] do %>
					<div id="watch" class="cat-action <%= doing? 'Watch' %>">Watch</div>
				<% end %>
				<%= link_to choose_cat_path @categories[0] do %>
					<div id="discuss" class="cat-action <%= doing? 'Discuss' %>">Discuss</div>
				<% end %>
			</div>

			<div class="bubble orange cat-page" id="quick-add"><span id="add-text">Quick Add</span></div>
			<%= form_tag quick_create_path, id: "quick-search", class: "hidden cat-page", remote: true do %>
				<%= text_field_tag :activities, nil, id: "self-search", :class => "head-4 quick-search-acts cat-page fb-enabled", placeholder: "Type to Add" %>
				<div class="hidden interest-info"></div>
				<%= hidden_field_tag :act_id %>
				<%= submit_tag "Add", id: "submit-quick-search", :class => "head-4 hidden" %>
			<% end %>

				<%= form_for @act, remote: true do |f| %>
					<%= f.text_field :name, :class => "act-name-input head-4 hidden fb-enabled", placeholder: "Suggest an Interest!" %>
					<div id="suggest-text" class="head-4">Interest not listed?</div>
					<%= f.hidden_field :category_id, value: @category.id %>
					<%= f.hidden_field :suggested_by, value: current_user.id %>
					<%= f.submit "Suggest", id: "submit-act", :class => "head-4 hidden" %>
				<% end %>


			<div id="categories-footer">
			<% if @interests < 8 %>
				<div id="cat-footer-content" class="head-4 gray">
					<div id="cat-footer-text">
						<p id="line-1">pick <span class="dark-gray" id="like-count"> <%= 8 - @interests %></span> or more options from any combination of categories to finish!</p>
						<p id="line-2">
							you can always come back to edit your choices
						</p>
					</div>
				</div>
				<div id="cat-actions">
					<div id="next-cat" class="head-3 hidden">
						<% if @category.name != "Discuss" %> 
							NEXT 
						<% end %>
					</div>
					<div id="finish" class="head-3 hidden">
						<%= link_to "FINISH", user_path(current_user) %>
					</div>
				</div>
			<% else %>
				<div id="cat-actions">
					<div id="next-cat" class="head-3">
						<% if @category.name != "Discuss" %> 
							NEXT 
						<% end %>
					</div>
					<div id="finish" class="head-3">
						<%= link_to "FINISH", user_path(current_user) %>
					</div>
				</div>
			<% end %>
	</div>

			
		</div>
	</div>


		<%= render partial: 'show', locals: {category: @category, act: @act, liked: @liked, not_liked: @not_liked, activities: @activities } %>
<script>
$('body').addClass('background-gray')
</script>

app/views/categories/tutorial.html+phone.erb
<script>
	$('.menu-icon').remove()
	$('.top-nav').append("<span class='next-tut hidden proceed'>Next</span>")
</script>

<div class="tutorial-container">
	<%= form_tag tutorial_select_path, id: "tutorial-form" do %>
		<div class="tut-question">
		  What school do you go to?
		</div>
		  <%= text_field_tag :school, nil, id: "tut-school", value: current_user.school || "University of Central Florida" %>
		<div class="tut-question">
		  Pick 2 characters that describe you best
		</div>
		<div class="tut-instructions">
			Then add 8 interests from any category<br>
			Don't worry, you can always edit your<br>
			interests or explore more categories later.
		</div>
		<%= hidden_field_tag :characters %>
		  <%= submit_tag "Submit", :class =>  "hidden" %>
	<% end %>

	<div class="characters-box">
		<% @characters[0..3].each do |char| %>
			<div class="char">
				<%= image_tag "#{char}.svg", :class => "char-image svg" %>
				<div class="char-label"><%= char.gsub("_", " ") %></div>
			</div>
		<% end %>
		<div class="char char-button">
			<div class="char-text">Pick at least 1 character</div>
		</div>
		<% @characters[4..7].each do |char| %>
			<div class="char">
				<%= image_tag "#{char}.svg", :class => "char-image svg" %>
				<div class="char-label"><%= char.gsub("_", " ") %></div>
			</div>
		<% end %>
	</div>
</div>


<script>
  $('img.svg').each(function(){
    var $img = $(this);
    var imgID = $img.attr('id');
    var imgClass = $img.attr('class');
    var imgURL = $img.attr('src');

    $.get(imgURL, function(data) {
        // Get the SVG tag, ignore the rest
        var $svg = $(data).find('svg');

        // Add replaced image's ID to the new SVG
        if(typeof imgID !== 'undefined') {
            $svg = $svg.attr('id', imgID);
        }
        // Add replaced image's classes to the new SVG
        if(typeof imgClass !== 'undefined') {
            $svg = $svg.attr('class', imgClass+' replaced-svg');
        }
        // Remove any invalid XML tags as per http://validator.w3.org
        $svg = $svg.removeAttr('xmlns:a');
        // Replace image with new SVG
        $img.replaceWith($svg);
    }, 'xml');
  });
</script>

app/views/categories/tutorial_select.html+phone.erb
<script>
	$('.menu-icon').remove()
	$('.menu-title').hide()
	$('.top-nav').append("<div class='tut-header unfinished'>Pick <span id='int-number'></span> More</div>")
	$('.top-nav').append("<div class='tut-header finished hidden'>Tap to Finish</div>")
	$('.top-nav').append("<a href='/tutorial'><span class='back-tut'>Back</span><a>")
</script>
<div class="interests-self tut">
		<div class="cat-collection">
			<% @categories.each do |cat| %>
					<div class="scroll-cat" id="c-<%= cat.id %>">
<pre class="scroll-cat-name"><% cat.mobile_name.each do |word| %><%= word %><br><% end %></pre>
						<%= image_tag cat.thumb_image_url, :class => "scroll-cat-pic" %>
						<div class="overlay"></div>
					</div>
					<div class="scroll-acts hidden">
						<% cat.activities.order(:name).each do |act| %>
							
								<div class="scroll-act <%= 'chosen' if @act_list.include?(act.id) %>">
									<%= link_to interests_path(act_id: act.id, nothing: true), remote: true, method: :post, class: 'add-other-act' do %>
										<div class="scroll-act-name"><%= act.super_short_name %></div>
									<% end %>
								</div>
						<% end %>
					</div>
			<% end %>
		</div>
	<div class="all-scroll-acts tut">
	</div>
	<div class="profile-actions green tut">
			<%= form_for @act, remote: true do |f| %>
				<%= f.text_field :name, :class => "act-name-input head-4 fb-enabled", placeholder: "Suggest"%>
				<%= f.hidden_field :category_id, value: @category.id %>
				<%= f.hidden_field :suggested_by, value: current_user.id %>
				<%= f.submit "Suggest", id: "submit-act", :class => "head-4 hidden" %>
			<% end %>

			<%= form_tag quick_create_path, id: "quick-search", remote: true do %>
				<%= text_field_tag :activities, nil, id: "self-search", :class => "head-4 quick-search-acts fb-enabled", placeholder: "Quick Search" %>
				<div class="hidden interest-info"></div>
				<%= hidden_field_tag :act_id %>
				<%= submit_tag "Add", id: "submit-quick-search", :class => "head-4 hidden" %>
			<% end %>
		</div>
</div>
<script>
	$(document).ready(function(){
		$($('.overlay')[1]).trigger('touchstart')
		var intCount = 8 - $('.cat-collection .chosen').length
		$('#int-number').text( intCount )
		if (intCount < 1) {
			$('.unfinished').hide()
			$('.finished').show()
		}
	})
</script>

<div id="welcome-tut" class="hidden">
	<div class="welcome-text">
		<div class="instructions-1 wel-text">Just a couple more things to know:</div>
		
		<div class="welcome-text">
			<!-- <div class="wel-text">Pictures are revealed once both<br>people message each other.</div>
		      <div class="wel-text"><span class="boy">Blue</span> text means this person is a guy, while <span class="girl">pink</span> means this person is a girl.<br>
			</div>
			<div class="wel-text">And once you start chatting, you can<br>
				<span class="light-turq">Invite</span> each other to hang out. 
			</div> -->
			<div class="wel-text">See what's happening on campus by checking <span class="light-turq">Events</span>This is a public panel where people can post open invites for events, chill sessions, or even study groups.</div>
		  <div class="wel-text">You can post your own invite whether you're hosting a party, looking for a study buddy, playing a pickup game, or just looking to meet someone random for a meal.
			</div>
		</div>
		<div class="wel-text s-s">Find people with similar interests<br>by using
			<span class="light-turq">Shuffle</span> or <span class="light-turq">Search</span> 
		</div>
	</div>
	<div class="welcome-similarities">
		<div class="wel-group">
			<span class="orange">Shared</span> Interests
			<div class="welcome-similarity mutual-box">
				<%= image_tag ('Mutual.svg'), :class => "wel-pic wel-mutual svg" %>
			</div>
		</div>
		<div class="wel-group">
			<span class="orange">Shared</span> Categories
			<div class="welcome-similarity sim-box">
				<%= image_tag ('Similar.svg'), :class => "wel-pic wel-sim svg" %>
			</div>
		</div>
	</div>
	

	<%= link_to events_path do %>
		<div class="wel-gotit">
			Got it!
		</div>
	<% end %>
</div>



<script>
  $('img.svg').each(function(){
    var $img = $(this);
    var imgID = $img.attr('id');
    var imgClass = $img.attr('class');
    var imgURL = $img.attr('src');

    $.get(imgURL, function(data) {
        // Get the SVG tag, ignore the rest
        var $svg = $(data).find('svg');

        // Add replaced image's ID to the new SVG
        if(typeof imgID !== 'undefined') {
            $svg = $svg.attr('id', imgID);
        }
        // Add replaced image's classes to the new SVG
        if(typeof imgClass !== 'undefined') {
            $svg = $svg.attr('class', imgClass+' replaced-svg');
        }
        // Remove any invalid XML tags as per http://validator.w3.org
        $svg = $svg.removeAttr('xmlns:a');
        // Replace image with new SVG
        $img.replaceWith($svg);
    }, 'xml');
  });
</script>